#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SailBotMainWindow(object):
    def setupUi(self, SailBotMainWindow):
        SailBotMainWindow.setObjectName("SailBotMainWindow")
        SailBotMainWindow.resize(714, 539)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SailBotMainWindow.sizePolicy().hasHeightForWidth())
        SailBotMainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SailBotMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 698, 501))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sailbotConnectionLayout = QtWidgets.QGridLayout()
        self.sailbotConnectionLayout.setContentsMargins(5, 5, 5, 5)
        self.sailbotConnectionLayout.setObjectName("sailbotConnectionLayout")
        self.startLogBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.startLogBtn.setObjectName("startLogBtn")
        self.sailbotConnectionLayout.addWidget(self.startLogBtn, 1, 2, 1, 1)
        self.connectBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.connectBtn.setObjectName("connectBtn")
        self.sailbotConnectionLayout.addWidget(self.connectBtn, 1, 0, 1, 1)
        self.disconnectBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.disconnectBtn.setObjectName("disconnectBtn")
        self.sailbotConnectionLayout.addWidget(self.disconnectBtn, 1, 1, 1, 1)
        self.stopLogBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.stopLogBtn.setObjectName("stopLogBtn")
        self.sailbotConnectionLayout.addWidget(self.stopLogBtn, 1, 3, 1, 1)
        self.connectionMainLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.connectionMainLbl.setMinimumSize(QtCore.QSize(0, 30))
        self.connectionMainLbl.setMaximumSize(QtCore.QSize(16777215, 30))
        self.connectionMainLbl.setObjectName("connectionMainLbl")
        self.sailbotConnectionLayout.addWidget(self.connectionMainLbl, 0, 0, 1, 4)
        self.gridLayout_2.addLayout(self.sailbotConnectionLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.ManualControlLayout = QtWidgets.QGridLayout()
        self.ManualControlLayout.setContentsMargins(5, 5, 5, 5)
        self.ManualControlLayout.setSpacing(6)
        self.ManualControlLayout.setObjectName("ManualControlLayout")
        self.tillerLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.tillerLbl.setObjectName("tillerLbl")
        self.ManualControlLayout.addWidget(self.tillerLbl, 3, 0, 1, 5)
        self.tillerRightBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.tillerRightBtn.sizePolicy().hasHeightForWidth())
        self.tillerRightBtn.setSizePolicy(sizePolicy)
        self.tillerRightBtn.setMinimumSize(QtCore.QSize(50, 25))
        self.tillerRightBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.tillerRightBtn.setObjectName("tillerRightBtn")
        self.ManualControlLayout.addWidget(self.tillerRightBtn, 5, 3, 1, 1)
        self.mainSailLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.mainSailLbl.setObjectName("mainSailLbl")
        self.ManualControlLayout.addWidget(self.mainSailLbl, 0, 0, 1, 5)
        self.mainSailNbLbl = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSailNbLbl.sizePolicy().hasHeightForWidth())
        self.mainSailNbLbl.setSizePolicy(sizePolicy)
        self.mainSailNbLbl.setMinimumSize(QtCore.QSize(30, 25))
        self.mainSailNbLbl.setMaximumSize(QtCore.QSize(30, 25))
        self.mainSailNbLbl.setObjectName("mainSailNbLbl")
        self.ManualControlLayout.addWidget(self.mainSailNbLbl, 1, 4, 1, 1)
        self.tillerNbLbl = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tillerNbLbl.sizePolicy().hasHeightForWidth())
        self.tillerNbLbl.setSizePolicy(sizePolicy)
        self.tillerNbLbl.setMinimumSize(QtCore.QSize(30, 10))
        self.tillerNbLbl.setMaximumSize(QtCore.QSize(30, 25))
        self.tillerNbLbl.setObjectName("tillerNbLbl")
        self.ManualControlLayout.addWidget(self.tillerNbLbl, 5, 4, 1, 1)
        self.tillerZeroBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.tillerZeroBtn.setMinimumSize(QtCore.QSize(50, 25))
        self.tillerZeroBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.tillerZeroBtn.setObjectName("tillerZeroBtn")
        self.ManualControlLayout.addWidget(self.tillerZeroBtn, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.ManualControlLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.tillerLeftBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tillerLeftBtn.sizePolicy().hasHeightForWidth())
        self.tillerLeftBtn.setSizePolicy(sizePolicy)
        self.tillerLeftBtn.setMinimumSize(QtCore.QSize(50, 25))
        self.tillerLeftBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.tillerLeftBtn.setObjectName("tillerLeftBtn")
        self.ManualControlLayout.addWidget(self.tillerLeftBtn, 5, 1, 1, 1)
        self.mainSailDnBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.mainSailDnBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.mainSailDnBtn.setObjectName("mainSailDnBtn")
        self.ManualControlLayout.addWidget(self.mainSailDnBtn, 2, 2, 1, 1)
        self.mainSailUpBtn = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.mainSailUpBtn.setMinimumSize(QtCore.QSize(20, 10))
        self.mainSailUpBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.mainSailUpBtn.setObjectName("mainSailUpBtn")
        self.ManualControlLayout.addWidget(self.mainSailUpBtn, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.ManualControlLayout, 2, 2, 1, 1)
        self.credits2 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.credits2.setObjectName("credits2")
        self.gridLayout_2.addWidget(self.credits2, 5, 2, 1, 1)
        self.credits1 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.credits1.setObjectName("credits1")
        self.gridLayout_2.addWidget(self.credits1, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.automaticControlLayout = QtWidgets.QGridLayout()
        self.automaticControlLayout.setContentsMargins(5, 5, 5, 5)
        self.automaticControlLayout.setObjectName("automaticControlLayout")
        self.holdDirectionTickBox = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.holdDirectionTickBox.setObjectName("holdDirectionTickBox")
        self.automaticControlLayout.addWidget(self.holdDirectionTickBox, 2, 1, 1, 1)
        self.holdSailTickBox = QtWidgets.QCheckBox(self.gridLayoutWidget_5)
        self.holdSailTickBox.setObjectName("holdSailTickBox")
        self.automaticControlLayout.addWidget(self.holdSailTickBox, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(50, 25, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.automaticControlLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.automaticControlLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.automaticControlLbl.setMinimumSize(QtCore.QSize(0, 25))
        self.automaticControlLbl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.automaticControlLbl.setObjectName("automaticControlLbl")
        self.automaticControlLayout.addWidget(self.automaticControlLbl, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.automaticControlLayout, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 3, 2, 1, 1)
        self.credits3 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.credits3.setObjectName("credits3")
        self.gridLayout_2.addWidget(self.credits3, 6, 2, 1, 1)
        self.realTimeSensorLayout = QtWidgets.QGridLayout()
        self.realTimeSensorLayout.setContentsMargins(5, 5, 5, 5)
        self.realTimeSensorLayout.setObjectName("realTimeSensorLayout")
        self.bnoTorqueLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoTorqueLbl.setObjectName("bnoTorqueLbl")
        self.realTimeSensorLayout.addWidget(self.bnoTorqueLbl, 3, 4, 1, 1)
        self.otherWifiSignalNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherWifiSignalNb.setObjectName("otherWifiSignalNb")
        self.realTimeSensorLayout.addWidget(self.otherWifiSignalNb, 9, 5, 1, 1)
        self.gpsTimeLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsTimeLbl.setObjectName("gpsTimeLbl")
        self.realTimeSensorLayout.addWidget(self.gpsTimeLbl, 5, 5, 1, 1)
        self.bnoCalLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoCalLbl.setObjectName("bnoCalLbl")
        self.realTimeSensorLayout.addWidget(self.bnoCalLbl, 3, 6, 1, 1)
        self.gpsLatNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsLatNb.setObjectName("gpsLatNb")
        self.realTimeSensorLayout.addWidget(self.gpsLatNb, 5, 1, 1, 2)
        self.bnoCalNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoCalNb.setObjectName("bnoCalNb")
        self.realTimeSensorLayout.addWidget(self.bnoCalNb, 3, 7, 1, 1)
        self.bnoOrientLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoOrientLbl.setObjectName("bnoOrientLbl")
        self.realTimeSensorLayout.addWidget(self.bnoOrientLbl, 3, 0, 1, 1)
        self.otherWifiLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherWifiLbl.setObjectName("otherWifiLbl")
        self.realTimeSensorLayout.addWidget(self.otherWifiLbl, 9, 4, 1, 1)
        self.gpsMainLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsMainLbl.setMinimumSize(QtCore.QSize(0, 25))
        self.gpsMainLbl.setObjectName("gpsMainLbl")
        self.realTimeSensorLayout.addWidget(self.gpsMainLbl, 4, 0, 1, 8)
        self.gpsLongLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsLongLbl.setObjectName("gpsLongLbl")
        self.realTimeSensorLayout.addWidget(self.gpsLongLbl, 5, 3, 1, 1)
        self.otherWifiAttenuationNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherWifiAttenuationNb.setObjectName("otherWifiAttenuationNb")
        self.realTimeSensorLayout.addWidget(self.otherWifiAttenuationNb, 9, 7, 1, 1)
        self.rotaryMainLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotaryMainLbl.setMinimumSize(QtCore.QSize(0, 25))
        self.rotaryMainLbl.setObjectName("rotaryMainLbl")
        self.realTimeSensorLayout.addWidget(self.rotaryMainLbl, 6, 0, 1, 8)
        self.rotaryWindAngle = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotaryWindAngle.setObjectName("rotaryWindAngle")
        self.realTimeSensorLayout.addWidget(self.rotaryWindAngle, 7, 2, 1, 2)
        self.gpsLongNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsLongNb.setObjectName("gpsLongNb")
        self.realTimeSensorLayout.addWidget(self.gpsLongNb, 5, 4, 1, 1)
        self.otherLoggerLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherLoggerLbl.setObjectName("otherLoggerLbl")
        self.realTimeSensorLayout.addWidget(self.otherLoggerLbl, 9, 0, 1, 2)
        self.bnoOrientNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoOrientNb.setObjectName("bnoOrientNb")
        self.realTimeSensorLayout.addWidget(self.bnoOrientNb, 3, 1, 1, 1)
        self.realTimeSensorLayoutMainLabel = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.realTimeSensorLayoutMainLabel.setMinimumSize(QtCore.QSize(0, 30))
        self.realTimeSensorLayoutMainLabel.setObjectName("realTimeSensorLayoutMainLabel")
        self.realTimeSensorLayout.addWidget(self.realTimeSensorLayoutMainLabel, 1, 0, 1, 8)
        self.bnoMainLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoMainLbl.setMinimumSize(QtCore.QSize(0, 25))
        self.bnoMainLbl.setObjectName("bnoMainLbl")
        self.realTimeSensorLayout.addWidget(self.bnoMainLbl, 2, 0, 1, 8)
        self.bnoTorqueNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoTorqueNb.setObjectName("bnoTorqueNb")
        self.realTimeSensorLayout.addWidget(self.bnoTorqueNb, 3, 5, 1, 1)
        self.otherLoggerStatus = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherLoggerStatus.setObjectName("otherLoggerStatus")
        self.realTimeSensorLayout.addWidget(self.otherLoggerStatus, 9, 2, 1, 2)
        self.otherMainLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherMainLbl.setMinimumSize(QtCore.QSize(0, 25))
        self.otherMainLbl.setObjectName("otherMainLbl")
        self.realTimeSensorLayout.addWidget(self.otherMainLbl, 8, 0, 1, 8)
        self.bnoPitchLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoPitchLbl.setObjectName("bnoPitchLbl")
        self.realTimeSensorLayout.addWidget(self.bnoPitchLbl, 3, 2, 1, 1)
        self.otherWifiNoiseNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.otherWifiNoiseNb.setObjectName("otherWifiNoiseNb")
        self.realTimeSensorLayout.addWidget(self.otherWifiNoiseNb, 9, 6, 1, 1)
        self.rotaryServoNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotaryServoNb.setObjectName("rotaryServoNb")
        self.realTimeSensorLayout.addWidget(self.rotaryServoNb, 7, 6, 1, 2)
        self.bnoPitchNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.bnoPitchNb.setObjectName("bnoPitchNb")
        self.realTimeSensorLayout.addWidget(self.bnoPitchNb, 3, 3, 1, 1)
        self.gpsTimeNb = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsTimeNb.setObjectName("gpsTimeNb")
        self.realTimeSensorLayout.addWidget(self.gpsTimeNb, 5, 6, 1, 2)
        self.gpsLatLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.gpsLatLbl.setObjectName("gpsLatLbl")
        self.realTimeSensorLayout.addWidget(self.gpsLatLbl, 5, 0, 1, 1)
        self.rotaryWindLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotaryWindLbl.setObjectName("rotaryWindLbl")
        self.realTimeSensorLayout.addWidget(self.rotaryWindLbl, 7, 0, 1, 2)
        self.rotaryServoLbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotaryServoLbl.setObjectName("rotaryServoLbl")
        self.realTimeSensorLayout.addWidget(self.rotaryServoLbl, 7, 4, 1, 1)
        self.rotaryServoAngle = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotaryServoAngle.setObjectName("rotaryServoAngle")
        self.realTimeSensorLayout.addWidget(self.rotaryServoAngle, 7, 5, 1, 1)
        self.gridLayout_2.addLayout(self.realTimeSensorLayout, 2, 0, 5, 1)
        SailBotMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SailBotMainWindow)
        self.statusbar.setObjectName("statusbar")
        SailBotMainWindow.setStatusBar(self.statusbar)
        self.actionCtrlLeftBtn = QtWidgets.QAction(SailBotMainWindow)
        self.actionCtrlLeftBtn.setObjectName("actionCtrlLeftBtn")
        self.actionCtrkRightBtn = QtWidgets.QAction(SailBotMainWindow)
        self.actionCtrkRightBtn.setObjectName("actionCtrkRightBtn")
        self.actionCtrlZeroBtn = QtWidgets.QAction(SailBotMainWindow)
        self.actionCtrlZeroBtn.setObjectName("actionCtrlZeroBtn")
        self.actionCtrkDownBtn = QtWidgets.QAction(SailBotMainWindow)
        self.actionCtrkDownBtn.setObjectName("actionCtrkDownBtn")
        self.actionCtrlUpBtn = QtWidgets.QAction(SailBotMainWindow)
        self.actionCtrlUpBtn.setObjectName("actionCtrlUpBtn")

        self.retranslateUi(SailBotMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SailBotMainWindow)

    def retranslateUi(self, SailBotMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SailBotMainWindow.setWindowTitle(_translate("SailBotMainWindow", "Sailing Bot Control Interface"))
        self.startLogBtn.setText(_translate("SailBotMainWindow", "Start Log"))
        self.connectBtn.setText(_translate("SailBotMainWindow", "Connect"))
        self.disconnectBtn.setText(_translate("SailBotMainWindow", "Disconnect"))
        self.stopLogBtn.setText(_translate("SailBotMainWindow", "Stop Log"))
        self.connectionMainLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Connection Management</span></p></body></html>"))
        self.tillerLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Tiller manual control</span></p></body></html>"))
        self.tillerRightBtn.setText(_translate("SailBotMainWindow", "->"))
        self.mainSailLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Main sail manual control</span></p></body></html>"))
        self.mainSailNbLbl.setText(_translate("SailBotMainWindow", "0"))
        self.tillerNbLbl.setText(_translate("SailBotMainWindow", "0"))
        self.tillerZeroBtn.setText(_translate("SailBotMainWindow", "Zero"))
        self.tillerLeftBtn.setText(_translate("SailBotMainWindow", "<-"))
        self.mainSailDnBtn.setText(_translate("SailBotMainWindow", "-"))
        self.mainSailUpBtn.setText(_translate("SailBotMainWindow", "+"))
        self.credits2.setText(_translate("SailBotMainWindow", "Made by cyrpaut, under GNU/GPL v3 licence"))
        self.credits1.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">SailingBot Remote control interface v 0.1</span></p></body></html>"))
        self.holdDirectionTickBox.setText(_translate("SailBotMainWindow", "Hold direction"))
        self.holdSailTickBox.setText(_translate("SailBotMainWindow", "Hold sail"))
        self.automaticControlLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Automatic control</span></p></body></html>"))
        self.credits3.setText(_translate("SailBotMainWindow", "<html><head/><body><p><a href=\"https://github.com/cyrpaut/sailingbot\"><span style=\" text-decoration: underline; color:#0000ff;\">See project on GitHub</span></a></p></body></html>"))
        self.bnoTorqueLbl.setText(_translate("SailBotMainWindow", "Torque:"))
        self.otherWifiSignalNb.setText(_translate("SailBotMainWindow", "0"))
        self.gpsTimeLbl.setText(_translate("SailBotMainWindow", "Time:"))
        self.bnoCalLbl.setText(_translate("SailBotMainWindow", "Cal:"))
        self.gpsLatNb.setText(_translate("SailBotMainWindow", "0"))
        self.bnoCalNb.setText(_translate("SailBotMainWindow", "0"))
        self.bnoOrientLbl.setText(_translate("SailBotMainWindow", "Orient:"))
        self.otherWifiLbl.setText(_translate("SailBotMainWindow", "Wifi:"))
        self.gpsMainLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">GPS Data</span></p></body></html>"))
        self.gpsLongLbl.setText(_translate("SailBotMainWindow", "Long:"))
        self.otherWifiAttenuationNb.setText(_translate("SailBotMainWindow", "0"))
        self.rotaryMainLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Rotary Encoder</span></p></body></html>"))
        self.rotaryWindAngle.setText(_translate("SailBotMainWindow", "0"))
        self.gpsLongNb.setText(_translate("SailBotMainWindow", "0"))
        self.otherLoggerLbl.setText(_translate("SailBotMainWindow", "Logger:"))
        self.bnoOrientNb.setText(_translate("SailBotMainWindow", "0"))
        self.realTimeSensorLayoutMainLabel.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Real-time Sensor Data</span></p></body></html>"))
        self.bnoMainLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">3 Axis BNO055</span></p></body></html>"))
        self.bnoTorqueNb.setText(_translate("SailBotMainWindow", "0"))
        self.otherLoggerStatus.setText(_translate("SailBotMainWindow", "off"))
        self.otherMainLbl.setText(_translate("SailBotMainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Other</span></p></body></html>"))
        self.bnoPitchLbl.setText(_translate("SailBotMainWindow", "Pitch:"))
        self.otherWifiNoiseNb.setText(_translate("SailBotMainWindow", "0"))
        self.rotaryServoNb.setText(_translate("SailBotMainWindow", "0"))
        self.bnoPitchNb.setText(_translate("SailBotMainWindow", "0"))
        self.gpsTimeNb.setText(_translate("SailBotMainWindow", "0"))
        self.gpsLatLbl.setText(_translate("SailBotMainWindow", "Lat:"))
        self.rotaryWindLbl.setText(_translate("SailBotMainWindow", "Windcock:"))
        self.rotaryServoLbl.setText(_translate("SailBotMainWindow", "Servo:"))
        self.rotaryServoAngle.setText(_translate("SailBotMainWindow", "0"))
        self.actionCtrlLeftBtn.setText(_translate("SailBotMainWindow", "CtrlLeftButton"))
        self.actionCtrlLeftBtn.setToolTip(_translate("SailBotMainWindow", "Left"))
        self.actionCtrlLeftBtn.setShortcut(_translate("SailBotMainWindow", "Left"))
        self.actionCtrkRightBtn.setText(_translate("SailBotMainWindow", "CtrkRightBtn"))
        self.actionCtrkRightBtn.setToolTip(_translate("SailBotMainWindow", "Right"))
        self.actionCtrkRightBtn.setShortcut(_translate("SailBotMainWindow", "Right"))
        self.actionCtrlZeroBtn.setText(_translate("SailBotMainWindow", "CtrlZeroBtn"))
        self.actionCtrlZeroBtn.setToolTip(_translate("SailBotMainWindow", "Zero"))
        self.actionCtrlZeroBtn.setShortcut(_translate("SailBotMainWindow", "Space"))
        self.actionCtrkDownBtn.setText(_translate("SailBotMainWindow", "CtrlDownBtn"))
        self.actionCtrkDownBtn.setToolTip(_translate("SailBotMainWindow", "Decrease main line"))
        self.actionCtrkDownBtn.setShortcut(_translate("SailBotMainWindow", "Down"))
        self.actionCtrlUpBtn.setText(_translate("SailBotMainWindow", "CtrlUpBtn"))
        self.actionCtrlUpBtn.setToolTip(_translate("SailBotMainWindow", "Increase main line"))
        self.actionCtrlUpBtn.setShortcut(_translate("SailBotMainWindow", "Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SailBotMainWindow = QtWidgets.QMainWindow()
    ui = Ui_SailBotMainWindow()
    ui.setupUi(SailBotMainWindow)
    SailBotMainWindow.show()
    sys.exit(app.exec_())

